name: Deploy docs
on:
  push:
    tags: ['v[0-9]+.*']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: ./.github/actions/setup
        with:
          python-version: 3.12

      - run: pip install -e .[all] pdoc3
      - run: python -m sambo._test -v
      - run: time .github/scripts/build-docs.sh

      - env:
          GH_PASSWORD: ${{ secrets.GH_PASSWORD }}
        run: .github/scripts/deploy-gh-pages.sh
